### ISSUE TITLE
the program cannot read https://github.com/zczcwh/PoseFormer  trained model

### ISSUE THREAD

**Issue by wileychan** [zczcwh/poseformer_demo#1]
Hello, thank you for your work.
Program cannot read https://github.com/zczcwh/PoseFormer trained model (*. bin）,for example, gt81f.bin
 What code needs to be modified？

**Comment by wileychan** [comment]
Traceback (most recent call last):
  File "demo/vis_poseformer.py", line 280, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis_poseformer.py", line 146, in get_pose3D
    model_dict[name] = pre_dict[name]
KeyError: 'Spatial_pos_embed'

**Comment by zczcwh** [comment]
The ckp for the demo is different from that one, please use the demo ckp. You can download it following the instruction in this repo.

**Comment by wileychan** [comment]
Thank you for your answer. 
But can you explain the difference between them? I want to know how model_10_5297.pth was trained.

**Comment by zczcwh** [comment]
You can check our PoseFormerv2 repo (https://github.com/QitaoZhao/PoseFormerV2). This ckp is compatible with PoseFormerv2 repo.

**Comment by zczcwh** [comment]
We follow the demo pipeline from MHFormer (https://github.com/Vegetebird/MHFormer) to retrain our network for a few epochs to get this ckp simply.

**Comment by WUJINHUAN** [comment]
Hello, thank you for your work.
Traceback (most recent call last):
  File "D:\datasets\poseformer_demo-main\demo\vis_poseformer.py", line 279, in <module>
    get_pose2D(video_path, output_dir)
  File "D:\datasets\poseformer_demo-main\demo\vis_poseformer.py", line 92, in get_pose2D
    keypoints, scores = hrnet_pose(video_path, det_dim=416, num_peroson=1, gen_output=True)
  File "D:\datasets\poseformer_demo-main\demo\lib\hrnet\gen_kpts.py", line 163, in gen_video_kpts
    keypoints = keypoints.transpose(1,0,2,3)  # (T, M, N, 2) --> (M, T, N, 2)
ValueError: axes don't match array
Why did such an error occur?
